#server:
#  tomcat:
#    # tomcat的URI编码
#    uri-encoding: UTF-8
#    # tomcat最大线程数，默认为200
#    max-threads: 800
#    # Tomcat启动初始化的线程数，默认值25
#    min-spare-threads: 30
server:
  port: 8008
  undertow:
    io-threads: 8   # 设置IO线程数, 它主要执⾏⾮阻塞的任务,它们会负责多个连接, 默认设置每个CPU核⼼⼀个线程
    # 不要设置过⼤，如果过⼤，启动项⽬会报错：打开⽂件数过多
    worker-threads: 256  # 阻塞任务线程池, 当执⾏类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
  # 它的值设置取决于系统线程执⾏任务的阻塞系数，默认值是IO线程数*8
    buffer-size: 1024  # 以下的配置会影响buffer,这些buffer会⽤于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间⼤⼩,越⼩的空间被利⽤越充分，不要设置太⼤，以免影响其他应⽤，合适即可
    buffers-per-region: 1024    # 每个区分配的buffer数量 , 所以pool的⼤⼩是buffer-size * buffers-per-region
    direct-buffers: true   # 是否分配的直接内存(NIO直接分配的堆外内存)


management:
  info:
    os:
      enabled: true
tcp:
  server:
    port: 8300

# 日志配置
logging:
  level:
    com.gisonwin.netty: debug
    org.springframework: info